config/routes.rb
Rails.application.routes.draw do
  devise_for :owners, controllers: {
    sessions: 'owners/sessions'
  }  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions'
  }

  resources :zombies do
      resources :brains
  end

  root to: 'zombies#index'

  devise_scope :owner do    
			get "sessions/owners/admins/List",
			to: "owners/sessions#List",
			as: "admins_List"
		end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/brain.rb
class Brain < ApplicationRecord
    belongs_to :zombie
    
    validates :flavor, presence: true
    validates :iq, numericality: {only_integer: true, message: "Sólo números!!"}
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all
  end

  # GET /brains/1
  # GET /brains/1.json
  def show
  end

  # GET /brains/new
  def new
    @brain = Brain.new
    @zombies = Zombie.all  
  end

  # GET /brains/1/edit
  def edit
  end

  # POST /brains
  # POST /brains.json
  def create
    # @brain = Brain.new(brain_params)
    @zombie = Zombie.find(params[:zombie_id]);
    @brain = @zombie.brains.create(brain_params);

    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'El cerebro ha sido creado' }
        format.json { render :show, status: :created, location: @brain }
        format.js #create.js.erb
      else
        format.html { render :new }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brains/1
  # PATCH/PUT /brains/1.json
  def update
    respond_to do |format|
      if @brain.update(brain_params)
        format.html { redirect_to @brain, notice: 'El cerebro a sido actualizado.' }
        format.json { render :show, status: :ok, location: @brain }
      else
        format.html { render :edit }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain.destroy
    respond_to do |format|
      format.html { redirect_to brains_url, notice: 'Ya no tiene el cerebro.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brain
      @brain = Brain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brain_params
      params.require(:brain).permit(:zombie_id,:flavor, :iq, :fresh)
    end
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/views/brains/_brain.html.erb
<table>
    <thead>
    <tr>
    <th>Tiempo: <%= time_ago_in_words(brain.created_at)%></th>
    <th>Sabor: <%= brain.flavor %></th>
    </thead>
 </table>

app/views/brains/_form.html.erb
<%= form_for(brain) do |f| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
<%= f.collection_select :zombie_id,Zombie.order(:name),:id,:name,include_blank:true %>
</div>

  <div class="field">
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>

<!-- Agregamos iq y fresh -->

 <div class="field">
    <%= f.label :iq %>
    <%= f.number_field :iq %>
  </div>

 <div class="field">
    <%= f.label :fresh %>
    <%= f.check_box :fresh %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brains/create.js.erb
var new_brain = $("<%= escape_javascript(render(:partial => @brain))%>").hide();
$('#brain').prepend(new_brain);
$('#brain_<%= @brain.id %>').fadeln('slow');
$('#new_brain')[0].reset();

app/views/brains/edit.html.erb
<h1>Editing Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Show', @brain %> |
<%= link_to 'Back', brains_path %>

app/views/brains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brains</h1>

<table>
  <thead>
    <tr>
      <th>Flavor</th>
        <th>Iq</th>
        <th>Fresh</th>
      <th colspan="3"></th>
    </tr>
      
  </thead>

  <tbody>
    <% @brains.each do |brain| %>
      <tr>
        <td><%= brain.flavor %></td>
        <td><%= brain.iq %></td>
        <td>
            <% if brain.fresh %>
            <%= image_tag 'brains/fresh.png', class: 'brains_fresh' %>
            <% else %>
            <%= image_tag 'brains/nofresh.png', class: 'brains_fresh' %>
            <% end %>
          </td>
        <td><%= link_to 'Mostrar', brain %></td>
        <td><%= link_to 'Editar', edit_brain_path(brain) %></td>
        <td><%= link_to 'Eliminar', brain, method: :delete, data: { confirm: 'Estas seguro compa?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo cerebro', new_brain_path %>

app/views/brains/new.html.erb
<h1>New Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Back', brains_path %>

app/views/brains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  <%= @brain.flavor %>
</p>
<p>
  <strong>Iq:</strong>
  <%= @brain.iq %>
</p>
<p>
  <strong>Fresh:</strong>
  <%= @brain.fresh %>
</p>

<%= link_to 'Editar', edit_brain_path(@brain) %> |
<%= link_to 'Volver', brains_path %>